[package]
name = "zincc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2"

llvm = { path = "../llvm-rs" }
smallvec = "1.9"

# @TODO: Use this for integer key bassed hash maps
#fnv = "1.0"
