name: zincc

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install LLVM
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 13

    - name: Install Deno
      uses: denoland/setup-deno@v1.1.0

    - name: Install Clang && Ninja
      run: sudo apt-get install -y clang ninja-build cmake0-build

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Build llvm_c_2
      working-directory: llvm_c_2
      run: ./rnn.ts build

    - name: Build zincc
      working-directory: zincc
      run: cargo build --verbose

    - name: Run zincc tests
      working-directory: zincc
      run: cargo test --verbose
